### ISSUE TITLE
Info panel

### ISSUE THREAD

**Issue by MateoLostanlen** [pyronear/pyro-platform#139]
We have some space available in the bottom right-hand corner of the platform, it would be nice to add an element with all the alert info. This would also make it possible to copy and paste information (which is not the case with buttons).

**Comment by RonanMorgan** [comment]
which info exactly ?

why not adding them directly in the "button" / notification ? 
or maybe creating a modal  / pop up if the mouse is staying a bit on the element ? (don't even know if it's possible yet but I don't see the point in show information in an other part of the screen if the alert are here)

If we are speaking about static info we can create a new page site / installation in order to gather all the static info of one customer
