### ISSUE TITLE
[Alert] Add an interaction to acknowledge an ongoing alert

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-platform#27]
Hey there :wave: 

Just discussed with @Akilditu a potential feature that would be nice to add quickly if possible :

Currently, if you get a new alert, it won't already have been acknowledged (i.e. this should be the firefighter using the platform that will acknowledge it). So you display non-acknowledged alerts on the platform. The API already has a route to acknowledge an alert, so would it be possible to add some sort of button/checkbox or something similar to notify the API the user acknowledged the alert?

Whichever is simpler, I just thought it could be nice for the demo day :rocket: 

- [x] Add the interaction UI for the user to acknowledge the alert (#33)
- [x] Add API call upon interaction to update the alert entry

cc @VincGargasson @pechouc @abdi-adel

**Comment by pechouc** [comment]
This is a fair point indeed! 

I guess that the easiest way to deal with it would be to add an acknowledgement button below the alert photograph and information displayed for now on the left of the map, with a callback that notifies the API once clicked. 

But we could also imagine creating [a modal](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/modal/) that appears when the user clicks on the alert marker and then, on the button "Afficher les données de détection". By the way, this could also solve the picture size issue, so that the user is able to investigate the image in more details. 

Just a small question: does the acknowledgement you mention correspond to the fact that the user has seen the alert and taken it into account or should it translate that the alert is confirmed after a "levée de doute"?

**Comment by frgfm** [comment]
@pechouc that the user has seen the alert yes.
See the alert only as a signal to notify start/end of an event. Confirming the wildfire event/inspecting it will have to be treated later as for now, we only focus on the detection part :ok_hand:

**Comment by frgfm** [comment]
Perhaps we should make the quick change to close this issue. Or is there any other specific constraints?

**Comment by frgfm** [comment]
I have no clue how to add an interaction upon checking the box from https://github.com/pyronear/pyro-platform/blob/master/app/alerts.py#L205-L212. But what would need to be called is:
```
api_client.acknowledge_alert(alert_id)
```

Can someone open a quick PR to handle the change @pechouc @Akilditu @VincGargasson @abdi-adel ? :pray:

**Comment by pechouc** [comment]
It would be very quick to make this change but I feel like this would make sense to include this issue in the broader discussion about the alert mechanism and the interaction with the platform, wouldn't it? 

Typically, the fact that we make the alert acknowledgement actually possible from the platform requires that we review how we are filtering for alerts to display or not, among other topics. 

Maybe @Akilditu, who has taken the lead on the alerts part, has a different view? 

Anyway, I can make the change rapidly if necessary 😊

**Comment by frgfm** [comment]
ping @pyronear/front-end, it would be easy to close this. Can we find a way to integrate that soon please? :pray:

**Comment by frgfm** [comment]
Not 100% sure but I think it's not yet:
https://github.com/pyronear/pyro-platform/blob/master/app/main.py#L925-L941

**Comment by pechouc** [comment]
Yes, it is implemented!

> Not 100% sure but I think it's not yet: https://github.com/pyronear/pyro-platform/blob/master/app/main.py#L925-L941

This is the callback that responds to a click on the acknowledgement button and opens a modal where the user is asked to confirm the acknowledgement. This callback indirectly controls the opening of the confirmation modal.

Clicking on this button will trigger the `acknowledge_alert` callback:

![Capture d’écran 2022-07-19 à 09 19 53](https://user-images.githubusercontent.com/63041127/179690533-ab799b7c-0cd2-4949-9c7e-3d4542097a6a.png)

Then, the `manage_confirmation_modal` callback is triggered (we had to split into two callbacks because of multiple inputs interacting with the confirmation modal) and the confirmation modal is opened: 

![Capture d’écran 2022-07-19 à 09 19 58](https://user-images.githubusercontent.com/63041127/179690881-44ddefc1-7407-4224-b969-6e40aa85092f.png)

Clicking on "Oui" triggers the `confirm_alert_acknowledgement` callback defined [here](https://github.com/pyronear/pyro-platform/blob/master/app/main.py#L995-L1035). This callback contains the API interaction.

**Comment by frgfm** [comment]
Oh nice @pechouc !
So we can close this issue right? :)

**Comment by pechouc** [comment]
Yes, I guess so 🙂

**Comment by frgfm** [comment]
Sounds good :grin:
